export const projects = [
  {
    title: 'E-Commerce',
    description: "Implemented HTML, CSS, JavaScript, to build a Front-End fully Responsive e-Commerce website - from start to finish. It is a simple website that allows users to view top-class footwears.",
      image: '/images/5.png',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://theshuu.netlify.app',
    visit: 'https://github.com/Billioma/theShu',
    id: 0,
  },
  {
    title: 'UI/UX',
    description:"Accessed a UI/UX design and developed a fully responsive Website. Advanced React & JavaScript topics was implemented in developing its features.",
    image: '/images/8.png',
    tags: ['React', 'JavaScript', 'CSS'],
    source: 'https://gpt3-js.netlify.app',
    visit: 'https://github.com/Billioma/gpt3',
    id: 1,
  },
  {
    title: 'Restaurant landing page',
    description: "Developed a landing page for a restaurant. Customers can access this site to view the food menu",
      tags: ['HTML', 'CSS', 'JavaScript'],
      image: '/images/9.jpg',
    source: 'https://chop-restaurant.netlify.app/',
    visit: 'https://github.com/Billioma/restaurant__website',
    id: 2,
    },
  {
    title: 'Video chat app',
    description: "This is a website built with Agora for video meetings with poll features as well as screen sharing features",
    tags: ['React', 'TypeScript', 'AgoraBuilder'],
    image: '/images/10.png',
    source: 'https://courtroom.netlify.app/create',
    visit: 'https://github.com/Billioma/videochat',
    id: 3,
  },
   {
    title: 'Real estate website',
    description: "Developed using Rapid API. This is a demo website where clients can take a peep at what may interest them and proceed with purchases",
    tags: ['React', 'Nextjs', 'chakra-ui'],
    image: '/images/1.jpg',
    source: 'https://oma-realestate.vercel.app',
    visit: 'https://github.com/Billioma/oma_realestate',
    id: 4,
  },
  {
    title: 'Hospital website',
    description: "A demo website for a clinic, allowing clients to glance through a landing page and an appointment booking page",
    tags: ['HTML', 'CSS', 'Vanilla JS'],
    image: '/images/2.jpg',
    source: 'https://ancilla-hospital.netlify.app/',
    visit: 'https://github.com/Billioma/hospital',
    id: 5,
  },
   {
    title: 'Task tracker',
    description: "Keep track of individual tasks, prioritize, and accomplish what’s most important.",
    tags: ['TypeScript'],
    image: '/images/3.png',
    source: 'task-tracker-indol.vercel.app/',
    visit: 'https://github.com/Billioma/task-tracker',
    id: 6,
  },
   {
    title: 'restaurant UI',
    description: "Landing page for a restaurant.",
    tags: ['React', 'CSS'],
    image: '/images/4.png',
    source: 'restaurant-page-ui.vercel.app/',
    visit: 'https://github.com/Billioma/restaurant-UI',
    id: 7,
  },
];

export const TimeLineData = [
  /*{ year: 2017, text: 'Started my journey', },*/
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Developed and implemented personal open source projects', },
  { year: 2020, text: 'Worked as a freelance developer',},
  { year: 2021, text: 'Front-end developer at 3REEN online', },
];
