import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/custom.css";
import Background from "../components/Background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <html lang="en">
      <body>
        <Background />
        <div className="relative">{children}</div>
      </body>
    </html>
  );
}
